from models import Synthesis, SynthesisStatus

SYNTHESIS_CATALOG: list[Synthesis] = [
    Synthesis(
        id=1,
        name="Получение диэтилового эфира",
        reagentName="Этиловый спирт",
        productName="Диэтиловый эфир",
        molarMassReagent=46.07,
        molarMassProduct=74.12,
        stoichiometricCoefficient=2.0,
        reagentMass=50.0,
        referenceYieldPercent=76.0,
        description="Синтез диэтилового эфира межмолекулярной дегидратацией этилового спирта в присутствии концентрированной серной кислоты при температуре 130-140°C.",
        imageKey="ether_synthesis.jpg",
        videoKey="ether_synthesis.mp4",
        status=SynthesisStatus.PUBLISHED,
        likedByUserIds=[101, 102, 103, 104],
    ),
    Synthesis(
        id=2,
        name="Получение йодоформа",
        reagentName="Ацетон",
        productName="Йодоформ",
        molarMassReagent=58.08,
        molarMassProduct=393.73,
        stoichiometricCoefficient=1.0,
        reagentMass=20.0,
        referenceYieldPercent=62.0,
        description="Йодоформная проба - взаимодействие ацетона с йодом в щелочной среде с образованием жёлтого осадка йодоформа.",
        imageKey="iodoform_synthesis.jpg",
        videoKey="iodoform_synthesis.mp4",
        status=SynthesisStatus.PUBLISHED,
        likedByUserIds=[101, 105],
    ),
    Synthesis(
        id=3,
        name="Получение ацетилена",
        reagentName="Карбид кальция",
        productName="Ацетилен",
        molarMassReagent=64.10,
        molarMassProduct=26.04,
        stoichiometricCoefficient=1.0,
        reagentMass=10.0,
        referenceYieldPercent=45.0,
        description="Гидролиз карбида кальция водой с выделением газообразного ацетилена и гидроксида кальция.",
        imageKey="acetylene_synthesis.jpg",
        videoKey="acetylene_synthesis.mp4",
        status=SynthesisStatus.PUBLISHED,
        likedByUserIds=[],
    ),
    Synthesis(
        id=4,
        name="Получение хлороформа",
        reagentName="Ацетон",
        productName="Хлороформ",
        molarMassReagent=58.08,
        molarMassProduct=119.38,
        stoichiometricCoefficient=1.0,
        reagentMass=15.0,
        referenceYieldPercent=55.0,
        description="Реакция галоформного расщепления ацетона гипохлоритом натрия.",
        imageKey="chloroform_synthesis.jpg",
        videoKey="chloroform_synthesis.mp4",
        status=SynthesisStatus.PUBLISHED,
        likedByUserIds=[102],
    ),
    Synthesis(
        id=5,
        name="Получение бромэтана",
        reagentName="Этиловый спирт",
        productName="Бромэтан",
        molarMassReagent=46.07,
        molarMassProduct=108.97,
        stoichiometricCoefficient=1.0,
        reagentMass=30.0,
        referenceYieldPercent=58.0,
        description="Взаимодействие этанола с бромидом натрия в кислой среде.",
        imageKey="bromoethane_synthesis.jpg",
        videoKey="bromoethane_synthesis.mp4",
        status=SynthesisStatus.ARCHIVED,
        likedByUserIds=[],
    ),
    Synthesis(
        id=6,
        name="Получение этилена",
        reagentName="Этиловый спирт",
        productName="Этилен",
        molarMassReagent=46.07,
        molarMassProduct=28.05,
        stoichiometricCoefficient=1.0,
        reagentMass=25.0,
        referenceYieldPercent=70.0,
        description="Дегидратация этанола над оксидом алюминия при нагревании.",
        imageKey="ethylene_synthesis.jpg",
        videoKey="ethylene_synthesis.mp4",
        status=SynthesisStatus.DRAFT,
        likedByUserIds=[],
    ),
]
